FROM node:22-alpine AS dependencies

WORKDIR /app

COPY sdk-client/package*.json ./

RUN npm ci


FROM dependencies AS build

COPY sdk-client/ ./

RUN npm run build


FROM nginxinc/nginx-unprivileged:1.27-alpine AS runtime

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
