apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "couple-games.configMapName" . }}
  labels:
    {{- include "couple-games.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  {{- range $k, $v := .Values.appConfig }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
